In [2]:
import numpy as np


## Creating Arrays with Zeeros, Ones or constants

In [3]:
zeros_array= np.zeros(10)
ones_array=np.ones(10)
constant_array=np.full(10,3)

In [4]:
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Converting list to arrays 

In [7]:
my_list=[2,3,4]
array_to_list= np.array(my_list)

In [8]:
array_to_list

array([2, 3, 4])

#### Generating Ranges of numbers 

In [9]:
range_of_num=np.arange(0,10)
range_of_num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Creating an array with Linear space 

linespace_array=np.linspace(0,2,10)
linespace_array

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

#### multi dimensional array

In [11]:
zero_matrix = np.zeros((10,5))

In [12]:
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
ones_Matrix=np.ones((5,8))
ones_Matrix

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
arr

array([[2, 3, 4],
       [4, 5, 6]])

In [15]:
arr[0]

array([2, 3, 4])

In [16]:
arr[:,1]

array([3, 5])

In [17]:
arr[1,:]

array([4, 5, 6])

## Generating random arrays 

In [18]:
np.random.seed(2)

In [19]:
random_array=np.random.rand(5,2)  #note that the rand method is used to generate a random decimal number beywen 0 and 1 
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
len(random_array)

5

In [21]:
 sample= sum(len(row) for row in random_array)

In [22]:
sample

10

In [23]:
random_array.size

10

In [24]:
np.size(random_array)

10

## Array Operations
- Numpy excels in performing mathematical operations on arrays efficiently.

### Element-wise Operations
You can perform operations on entire arrays element by element:

In [25]:
arr= arr +1 # add one to each element


In [26]:
arr

array([[3, 4, 5],
       [5, 6, 7]])

In [27]:
arr + 2

array([[5, 6, 7],
       [7, 8, 9]])

In [28]:
arr1=np.ones (4)
arr2=np.full(4,3)

In [29]:
result= sum(arr1,arr2)
result

array([7., 7., 7., 7.])

In [30]:
result= arr1/arr2

In [31]:
result

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [32]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]

In [33]:
greater_than_2 

array([False, False,  True,  True])

In [34]:
max_value=arr.max()
min_value=arr.min()
summation=arr.sum()
mean_value=arr.mean()
std_deviation=arr.std()

In [35]:
print(mean_value)


2.5


In [36]:
print(std_deviation)

1.118033988749895


# Linear algebra 

- Vector operations
- Multiplication
- Vector-vector multiplication
- Matrix-vector multiplication
- Matrix-matrix multiplication
- Identity matrix
- Inverse

## Vector Operations 

In [37]:
u=np.array([2,3,4,5])
v=np.array([7,8,9,3])

u+ v

array([ 9, 11, 13,  8])

In [38]:
u-v

array([-5, -5, -5,  2])

In [39]:
2*v

array([14, 16, 18,  6])

In [40]:
type(u.shape[0])

int

## Vector Multiplication

In [41]:
def vector_vectpor_multiplication (u,v):
    assert u.shape[0]==v.shape[0], "the dimensions of both vectors must be the same"
    n= u.shape[0]
    container=[]
    for x in range(n):
        dot=u[x]*v[x]
        container.append(dot)
    result_mul= sum(container)
    return result_mul
        

In [42]:
dot_product=vector_vectpor_multiplication(u,v)

In [ ]:
dot_product

np.int64(89)

In [44]:
def vector_vector_multiplication1(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [45]:
dot_product=vector_vector_multiplication1(u,v)
dot_product

np.float64(89.0)

## Matrix vector multiplication

In [46]:
def matrix_vector_multiplication(v,u):
    
    assert u.shape[0]==v.shape[1], "number of vector rows(entries) must match matrix column number"
    n=v.shape[0]
    r=v.shape[1]
    container=[]
    for i in range(n):
        s=0
        for q in range(r):
            s=s+v[i,q]*u[q]
        container.append(s)
    return container 
        
            

In [47]:
u=np.array([1,3])
v=np.array([[3,2],[2,1],[2,2]])

In [48]:
matrix_vector_multiplication(v,u)

[np.int64(9), np.int64(5), np.int64(8)]

In [ ]:
v

array([[3, 2],
       [2, 1],
       [2, 2]])

In [ ]:
v.shape

(3, 2)

In [51]:
v[0,1]

np.int64(2)

In [ ]:
u[0]

np.int64(1)

In [53]:
def matrix_matrix_multiplication (U,V):
    assert U.shape[1]==V.shape[0], "The number of columns in 𝐴 must equal the number of rows in 𝐵"
    C= np.zeros([U.shape[0],V.shape[1]])
    n= C.shape[0]
    r=C.shape[1]
    for n in range(C.shape[0]):
        C[n,:]= matrix_vector_multiplication(V.T,U[n,:])
    return C
        

In [54]:
A=np.array([[7,8],[9,10]])
B=np.array([[1,2],[3,4],[5,6]])

In [ ]:
A

array([[ 7,  8],
       [ 9, 10]])

In [56]:
matrix_matrix_multiplication(B,A)

array([[ 25.,  28.],
       [ 57.,  64.],
       [ 89., 100.]])

In [57]:
C= np.zeros([2,3])
C

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
import numpy as np

def matrix_vector_multiplication(v, u):
    assert u.shape[0] == v.shape[1], "Number of vector rows(entries) must match matrix column number"
    n = v.shape[0]  # Number of rows in matrix
    r = v.shape[1]  # Number of columns in matrix (must match vector length)
    
    container = []
    for i in range(n):
        s = 0
        for q in range(r):
            s += v[i, q] * u[q]
        container.append(s)
    
    return np.array(container)  # Return as NumPy array for consistency

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0], "The number of columns in A must equal the number of rows in B"
    
    # Create result matrix C with zeros
    C = np.zeros((U.shape[0], V.shape[1]))  
    
    # Corrected loop variable (use `i` instead of overwriting `n`)
    for i in range(U.shape[0]):  
        C[i, :] = matrix_vector_multiplication(V, U[i, :])  # Row-wise multiplication
    
    return C

# Define matrices
A = np.array([[7, 8], [9, 10]])
B = np.array([[1, 2], [3, 4], [5, 6]])

# Compute multiplication B × A
result = matrix_matrix_multiplication(B, A)
print(result)


[[ 23.  29.]
 [ 53.  67.]
 [ 83. 105.]]


In [ ]:
import numpy as np

def matrix_vector_multiplication(v, u):
    """Performs the dot product of matrix v (m×n) with vector u (n,)"""
    assert v.shape[1] == u.shape[0], "Number of vector entries must match matrix column count"
    
    n = v.shape[0]  # Number of rows in matrix
    r = v.shape[1]  # Number of columns in matrix (should match length of u)
    
    container = []
    
    for i in range(n):
        s = 0
        for q in range(r):
            s += v[i, q] * u[q]  # Element-wise multiplication and summation
        container.append(s)
    
    return np.array(container)  # Ensure output is a NumPy array

def matrix_matrix_multiplication(U, V):
    """Performs matrix-matrix multiplication by treating each row of U as a vector"""
    assert U.shape[1] == V.shape[0], "The number of columns in A must equal the number of rows in B"
    
    # Create the result matrix C with zeros
    C = np.zeros((U.shape[0], V.shape[1]))  
    
    for i in range(U.shape[0]):  
        C[i, :] = matrix_vector_multiplication(V, U[i, :])  # Multiply each row of U with V
    
    return C

# Define matrices
A = np.array([[7, 8], [9, 10]])
B = np.array([[1, 2], [3, 4], [5, 6]])

# Compute B × A
result = matrix_matrix_multiplication(B, A)
print(result)


[[ 23.  29.]
 [ 53.  67.]
 [ 83. 105.]]


In [60]:
import numpy as np

def matrix_vector_multiplication(v, u):
    """Computes the dot product of matrix v (n×m) with vector u (m,)"""
    assert v.shape[1] == u.shape[0], "Number of vector entries must match matrix column count"
    
    n = v.shape[0]  # Number of rows in matrix
    container = []
    
    for i in range(n):
        s = 0
        for q in range(v.shape[1]):  # Iterate over columns of `v`
            s += v[i, q] * u[q]  # Dot product computation
        container.append(s)
    
    return np.array(container)

def matrix_matrix_multiplication(U, V):
    """Computes matrix-matrix multiplication by treating each row of U as a vector"""
    assert U.shape[1] == V.shape[0], "The number of columns in U must equal the number of rows in V"
    
    C = np.zeros((U.shape[0], V.shape[1]))  # Resulting matrix shape (m, p)

    for i in range(U.shape[0]):  
        C[i, :] = matrix_vector_multiplication(V.T, U[i, :])  # Correct order
    
    return C

# Define matrices
A = np.array([[7, 8], [9, 10]])
B = np.array([[1, 2], [3, 4], [5, 6]])

# Compute B × A
result = matrix_matrix_multiplication(B, A)
print(result)


[[ 25.  28.]
 [ 57.  64.]
 [ 89. 100.]]


# Pandas

In [61]:
import pandas as pd

In [62]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]



In [63]:
df=pd.DataFrame(data,columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

Series
Columns in a data frame - series. To access it, use dot or brackets

In [64]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [65]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

Note that if a name contains space you can't use dot name

In [66]:
#use a list to select a subset of column
df[['Make','Model','MSRP']] 

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

# Index

In [67]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [68]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [69]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [70]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: 0, dtype: object

In [ ]:
df.iloc[[2,3,0]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2   Lotus   Elise  2010      218.0                 4            MANUAL   
3     GMC  Acadia  2017      194.0                 4         AUTOMATIC   
0  Nissan  Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
3       4dr SUV  34450  
0         sedan   2000

In [72]:
idx=np.arange(5)

In [ ]:
np.random.seed(2)
np.random.shuffle(idx)
idx

array([2, 4, 1, 3, 0])

In [74]:
df.iloc[idx]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

In [75]:
df=df.iloc[idx]

In [ ]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

In [ ]:
df.iloc[[0,1,2]]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150

In [78]:
df.index

Index([2, 4, 1, 3, 0], dtype='int64')

In [79]:
df.loc[[0,1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990

In [ ]:
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0    Lotus     Elise  2010      218.0                 4            MANUAL   
1   Nissan  Frontier  2017      261.0                 6            MANUAL   
2  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
0   convertible  54990  
1        Pickup  32340  
2         Sedan  27150  
3       4dr SUV  34450  
4         sedan   2000

In [81]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

# String Operations

In [82]:
df['Vehicle_Style']

2    convertible
4         Pickup
1          Sedan
3        4dr SUV
0          sedan
Name: Vehicle_Style, dtype: object

In [83]:
df.Vehicle_Style.str.lower().inplace=True

In [84]:
df.Vehicle_Style

2    convertible
4         Pickup
1          Sedan
3        4dr SUV
0          sedan
Name: Vehicle_Style, dtype: object

In [85]:
df['Vehicle_Style'].str.lower().str.replace(' ','_')

2    convertible
4         pickup
1          sedan
3        4dr_suv
0          sedan
Name: Vehicle_Style, dtype: object

In [86]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [87]:
df.columns= df.columns.str.lower().str.replace(' ','_')

In [88]:
df.columns

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp'],
      dtype='object')

In [ ]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  vehicle_style   msrp  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

In [90]:
df.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders       int64
transmission_type     object
vehicle_style         object
msrp                   int64
dtype: object

In [91]:
df.dtypes.index

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp'],
      dtype='object')

In [92]:
df.dtypes[df.dtypes=='object']

make                 object
model                object
transmission_type    object
vehicle_style        object
dtype: object

In [93]:
w=list(df.dtypes[df.dtypes=='object'].index)

In [94]:
w

['make', 'model', 'transmission_type', 'vehicle_style']

In [95]:
string_columns = df.dtypes[df.dtypes=='object'].index

In [96]:
for col in string_columns:
    df[col]=df[col].str.lower().str.replace(' ','_')


In [97]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
2    lotus     elise  2010      218.0                 4            manual   
4   nissan  frontier  2017      261.0                 6            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
3      gmc    acadia  2017      194.0                 4         automatic   
0   nissan    stanza  1991      138.0                 4            manual   

  vehicle_style   msrp  
2   convertible  54990  
4        pickup  32340  
1         sedan  27150  
3       4dr_suv  34450  
0         sedan   2000

# Summarizing Operations EDA

In [98]:
df.msrp

2    54990
4    32340
1    27150
3    34450
0     2000
Name: msrp, dtype: int64

In [99]:
df.msrp.mean()

np.float64(30186.0)

In [100]:
df.msrp.sum()

np.int64(150930)

In [101]:
df.msrp.min(), df.msrp.max(), df.msrp.mean(), df.msrp.std()

(np.int64(2000),
 np.int64(54990),
 np.float64(30186.0),
 np.float64(18985.044903818372))

In [102]:
df.msrp.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: msrp, dtype: float64

In [ ]:
df.describe().round(2)

year  engine_hp  engine_cylinders      msrp
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [105]:
df.make.nunique()

4

In [106]:
df.make.value_counts(sort=True)

make
nissan     2
lotus      1
hyundai    1
gmc        1
Name: count, dtype: int64

In [107]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            1
engine_cylinders     0
transmission_type    0
vehicle_style        0
msrp                 0
dtype: int64

In [108]:
df.engine_hp.isnull()

2    False
4    False
1     True
3    False
0    False
Name: engine_hp, dtype: bool

In [109]:
df.engine_hp.fillna(0)

2    218.0
4    261.0
1      0.0
3    194.0
0    138.0
Name: engine_hp, dtype: float64

In [110]:
df.engine_hp.fillna(df.engine_hp.mean())

2    218.00
4    261.00
1    202.75
3    194.00
0    138.00
Name: engine_hp, dtype: float64

In [111]:
df.reset_index(inplace=True,drop=True)

In [114]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0    lotus     elise  2010      218.0                 4            manual   
1   nissan  frontier  2017      261.0                 6            manual   
2  hyundai    sonata  2017        NaN                 4         automatic   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan    stanza  1991      138.0                 4            manual   

  vehicle_style   msrp  
0   convertible  54990  
1        pickup  32340  
2         sedan  27150  
3       4dr_suv  34450  
4         sedan   2000

In [116]:
df.engine_hp = df.engine_hp.fillna(df.engine_hp.mean())
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0    lotus     elise  2010     218.00                 4            manual   
1   nissan  frontier  2017     261.00                 6            manual   
2  hyundai    sonata  2017     202.75                 4         automatic   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan    stanza  1991     138.00                 4            manual   

  vehicle_style   msrp  
0   convertible  54990  
1        pickup  32340  
2         sedan  27150  
3       4dr_suv  34450  
4         sedan   2000

In [117]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0    lotus     elise  2010     218.00                 4            manual   
1   nissan  frontier  2017     261.00                 6            manual   
2  hyundai    sonata  2017     202.75                 4         automatic   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan    stanza  1991     138.00                 4            manual   

  vehicle_style   msrp  
0   convertible  54990  
1        pickup  32340  
2         sedan  27150  
3       4dr_suv  34450  
4         sedan   2000

Grouping 

- SELECT
    tranmission_type,
    AVG(msrp)
- FROM
    cars
- GROUP BY
    transmission_type

In [118]:
df.groupby('transmission_type').msrp.mean()

transmission_type
automatic    30800.000000
manual       29776.666667
Name: msrp, dtype: float64

In [119]:
df_group=df.groupby('transmission_type').msrp.agg(['mean','count'])
df_group

mean  count
transmission_type                     
automatic          30800.000000      2
manual             29776.666667      3

# Object-Oriented Programming (OOP)

Object-Oriented Programming (OOP) is a fundamental concept in Python (and many other programming languages) that helps you organize your code in a way that’s reusable, modular, and easy to understand.

OOP focuses on:

1. Classes: Blueprints that describe the structure and behavior of objects.
2. Objects (Instances): Real-world entities created using class definitions.
3. Methods: Functions defined within a class to manipulate data or perform actions.
4. Attributes (Fields): Data or properties that describe the object.Data that belongs to a class or object.

For example, if you’re building a program for a car, a Car object might have attributes like color, model, and speed, and methods like drive() or brake().


- __Principles__:
1. Encapsulation: Bundling related properties and behaviors together.
2. Inheritance: Reusing and extending existing classes.
3. Polymorphism: Using a single interface to represent different data types or classes.
4. Abstraction: Hiding complex details and exposing only the necessary parts.
By learning OOP, you will be able to write code that is easier to maintain, debug, and extend.



## 2. Defining a Class and Creating Objects
- Class Definition
In Python, a class is defined using the class keyword followed by the class name. By convention, class names are written in CamelCase:

In [120]:
class Person:
    pass

In [121]:
person1=Person()
person1=Person()

In [122]:
print(type(person1))

<class '__main__.Person'>


## 3. Adding Attributes and Methods

3.1 The "__ __init__ __" Method (Constructor)
In Python, the __init__ method initializes an object’s attributes when it is created. It is often referred to as the constructor, though Python uses this special naming convention:

In [123]:
class Person():
    def __init__(self,name,age):
        self.name = name #instance attribute
        self.age = age   #instance attribute 

    def greet(self):
        print(f"Hello, my name is {self.name} and I am {self.age} years old.")

     


- def __ __init__ __(self, name, age): The self parameter refers to the current instance of the class.
- self.name and self.age: These are instance attributes unique to each created object.

## 3.2 Instantiating the Enhanced Class

In [124]:
person1=Person('ade',30)
person2=Person('Uche',25)

person1.greet()
person2.greet()

Hello, my name is ade and I am 30 years old.
Hello, my name is Uche and I am 25 years old.


Here, person1 and person2 have different name and age values, demonstrating how each object can maintain its own data.

In [125]:
class Dog:
    #CLass attribute (shared by all instance of the class)
    species="Canis familiaris"
    
    def __init__(self, name, age):
        # instance attribute unique to each object
        self.name = name 
        self.age = age
    
    # instance method (a function that belongs to the object)
    def bark(self):
        return f"{self.name} says woof!"
    
    def get_info(self):
        return f"{self.name} is {self.age} years old and is a {self.species}."


In [126]:
dog1=Dog("Buddy",3)
dog2=Dog("Max",5)

print(dog1.name)
print(dog2.species)
print(dog1.bark())
print(dog2.get_info())

Buddy
Canis familiaris
Buddy says woof!
Max is 5 years old and is a Canis familiaris.


## 4. Class Attributes vs. Instance Attributes
- Instance attributes: Defined inside the __init__ method using self.attribute_name. They are unique to each instance.

- Class attributes: Defined directly in the class body, shared across all instances.

In [127]:
class Person:
    species="Homo sapien"

    def __init__(self, name, age):
        self.name = name # instance attribute unique to each object
        self.age =age  #instance attribute unique to each object

    def greet (self):
        print (f"Hello, my name is {self.name}.")

    def profile (self):
        return f"This is {self.name} and he is a {self.species} and is {self.age} years old."
    

In [128]:
person1=Person("Audu",30)
person2=Person("Pauline",45)

print(person1.age)
print(person2.name)
print(person2.profile())
print(person1.greet())

30
Pauline
This is Pauline and he is a Homo sapien and is 45 years old.
Hello, my name is Audu.
None


## Encapsulation
Encapsulation means hiding the internal details of how an object works. In Python, we use private attributes (prefixed with _ or _ _) to restrict direct access.

In [141]:
class BankAcoount:
    def __init__(self, owner, balance=500):
        self.owner=owner
        self.__balance=balance #private attribute

    def deposit(self,amount):
        if amount > 0:
            self.__balance += amount
            return f"You have deposited ${amount}, your new balance is ${self.__balance}"
        else:
            return f"Invalid amount."
        
    def withdrawal(self,amount):
        if 0 < amount < self.__balance:
            self.__balance -=amount
            return f"You withdrew ${amount}, your new balance is {self.__balance}. Thank you "
        else:
            return f"Insufficient funds"
        
    def get_balance(self):
        return f"Balance: ${self.__balance}"
    
#create an object
account=BankAcoount("Alice")

print(account.deposit(5000))

print(account.withdrawal(3000))
        
        

You have deposited $5000, your new balance is $5500
You withdrew $3000, your new balance is 2500. Thank you 


In [142]:
account.get_balance()

'Balance: $2500'

In [148]:
print(account.__balance)

AttributeError: 'BankAcoount' object has no attribute '__balance'


# 5. Inheritance
- Concept of Inheritance

Inheritance allows one class (called the child or subclass) to inherit attributes and methods from another class (called the parent or superclass). The child class can reuse, extend, or override the parent class functionality.

- Example:

Suppose we have a Vehicle class as a parent class. We can create a Car class that inherits from Vehicle.

In [3]:
class Vehicle:
    def __init__(self,brand,model):
        self.brand=brand
        self.model=model

    def start_engine(self):
        print(f'{self.brand} {self.model} start engine.')

class Car(Vehicle):
    def __init__(self,brand,model,num_doors):
        #use super() to call the parent class's __init__ method
        super().__init__(brand,model)
        self.num_doors=num_doors

    def open_trunk(self):
        print(f'opening the trunk of the {self.brand} {self.model}')



#create an object of the car class
my_car=Car("Toyota","Camry",4)

print(my_car.brand)
print(my_car.model)


Toyota
Camry


In [4]:
my_car.open_trunk()

opening the trunk of the Toyota Camry


In [5]:
my_car.num_doors

4

### Example 2

In [6]:
# Parent Class
class Animal:
    def __init__(self,name):
        self.name= name 

    def speak(self):
        return f'{self.name} makes a sound.'
    
#child class
class Cat(Animal):
    def speak(self):
        return f"{self.name} says meow"
    

#create objects

animal=Animal("Generic Animal")
cat=Cat("Whisker")

print(animal.name)
print(animal.speak())
print(cat.speak())

Generic Animal
Generic Animal makes a sound.
Whisker says meow


## Method Overriding
When you want a child class to have a different implementation of a method that already exists in the parent class, you override it by redefining the method under the same name. For instance, if a Car needs a specific engine start procedure, we can override the start_engine method:

In [15]:
class Car(Vehicle):
    def __init__(self,brand,model,num_doors):
        super().__init__(brand,model)
        self.num_doors =num_doors

    def start_engine(self):
        return (f"Starting {self.brand} {self.model} in a special way for cars.")

    def open_trunk(self):
        print(f"Opening the trunk of the {self.brand} {self.model}")


my_new_car=Car("Honda","Accord",4)
print(my_new_car.start_engine())

Starting Honda Accord in a special way for cars.


## Polymorphism
Polymorphism enables you to call the same method name on different objects, and each object will respond in a way appropriate to its class. Suppose we have a set of different classes that share a method called start_engine:

In [16]:
class Motorcycle(Vehicle):
    def start_engine(self):
        return f"{self.brand} {self.model} motorcycle engine roars to life"
    

vehicles= [
    Car("Toyota","Camry",4),
    Motorcycle("Harley-Davidson","street 750"),
]

for v in vehicles:
    print(v.start_engine())

Starting Toyota Camry in a special way for cars.
Harley-Davidson street 750 motorcycle engine roars to life


#### Example 2

In [17]:
class Dog (Animal):
    def speak(self):
        return f"{self.name} says woof!"
    
class Bird(Animal):
    def speak(self):
        return f"{self.name} says chirp!"
    
#create objects
dog=Dog("Buddy")
bird=Bird("Tweety")

for animal in [dog, bird]:
    print(animal.speak())

Buddy says woof!
Tweety says chirp!


## Putting It All Together: A Comprehensive Example

In [19]:
class Product:
    def __init__(self, name, price):
        self.name = name
        self.price = price

    def __str__(self):
        return f"{self.name} (${self.price})"


class ShoppingCart:
    def __init__(self):
        self._products = []

    def add_product(self, product):
        self._products.append(product)
        print(f"Added {product.name} to the cart.")

    def remove_product(self, product_name):
        for product in self._products:
            if product.name == product_name:
                self._products.remove(product)
                print(f"Removed {product_name} from the cart.")
                break
        else:
            print(f"Product {product_name} not found in the cart.")

    def calculate_total(self):
        return sum([p.price for p in self._products])

    def checkout(self):
        total_cost = self.calculate_total()
        print(f"Checking out. Total cost: ${total_cost:.2f}")
        # Here, you might process payment or generate an invoice, for example.

    def __str__(self):
        product_list = ", ".join(str(p) for p in self._products)
        return f"ShoppingCart with items: {product_list}"


# Usage
apple = Product("Apple", 1.50)
bread = Product("Bread", 2.00)
milk = Product("Milk", 3.00)

cart = ShoppingCart()
cart.add_product(apple)
cart.add_product(bread)
cart.add_product(milk)

print(cart)  # Print cart details
cart.remove_product("Bread")
cart.checkout()


Added Apple to the cart.
Added Bread to the cart.
Added Milk to the cart.
ShoppingCart with items: Apple ($1.5), Bread ($2.0), Milk ($3.0)
Removed Bread from the cart.
Checking out. Total cost: $4.50


In [43]:
class Product:
    def __init__(self,name,price):
        self.name=name
        self.price=price

    def __str__(self):
        return f"{self.name} - ${self.price}"
    
class ShoppingCart:
    def __init__(self):
        self.__products=[]

    def add_product(self,product):
        self.__products.append(product)
        print (f"Added {product.name} to the cart")
    
    def remove_product(self,product):
        for p in self.__products:
            if p.name== product:
                self.__products.remove(p)
                print(f"Removed {product} from the cart")
                break
        else:
                print(f"Product {product} not found in the cart")
    
    def calculate_total(self):
        return sum([p.price for p in self.__products])
    
    def checkout(self):
        total_cost= self.calculate_total()
        return f"checking out. Total cost: ${total_cost:.2f}"
    
    def __str__(self):
        product_list=','.join(str(p) for p in self.__products)
        return f'shoppingCart with items: {product_list}'

#usage 
apple=Product("Apple",1.50)
bread=Product("Bread", 2.00)
milk=Product("Milk",3.00)

cart=ShoppingCart()
cart.add_product(apple)
cart.add_product(bread)
cart.add_product(milk)

print(cart)

    


Added Apple to the cart
Added Bread to the cart
Added Milk to the cart
shoppingCart with items: Apple - $1.5,Bread - $2.0,Milk - $3.0


In [44]:
cart.remove_product(milk)

Product Milk - $3.0 not found in the cart


In [45]:
print(cart)

shoppingCart with items: Apple - $1.5,Bread - $2.0,Milk - $3.0
