In [23]:
import numpy as np


## Creating Arrays with Zeeros, Ones or constants

In [24]:
zeros_array= np.zeros(10)
ones_array=np.ones(10)
constant_array=np.full(10,3)

In [25]:
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [26]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Converting list to arrays 

In [28]:
my_list=[2,3,4]
array_to_list= np.array(my_list)

In [29]:
array_to_list

array([2, 3, 4])

#### Generating Ranges of numbers 

In [30]:
range_of_num=np.arange(0,10)
range_of_num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#Creating an array with Linear space 

linespace_array=np.linspace(0,2,10)
linespace_array

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

#### multi dimensional array

In [32]:
zero_matrix = np.zeros((10,5))

In [33]:
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
ones_Matrix=np.ones((5,8))
ones_Matrix

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
arr

array([[2, 3, 4],
       [4, 5, 6]])

In [36]:
arr[0]

array([2, 3, 4])

In [37]:
arr[:,1]

array([3, 5])

In [38]:
arr[1,:]

array([4, 5, 6])

## Generating random arrays 

In [39]:
np.random.seed(2)

In [40]:
random_array=np.random.rand(5,2)  #note that the rand method is used to generate a random decimal number beywen 0 and 1 
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [41]:
len(random_array)

5

In [42]:
 sample= sum(len(row) for row in random_array)

In [43]:
sample

10

In [44]:
random_array.size

10

In [45]:
np.size(random_array)

10

## Array Operations
- Numpy excels in performing mathematical operations on arrays efficiently.

### Element-wise Operations
You can perform operations on entire arrays element by element:

In [46]:
arr= arr +1 # add one to each element


In [47]:
arr

array([[3, 4, 5],
       [5, 6, 7]])

In [48]:
arr + 2

array([[5, 6, 7],
       [7, 8, 9]])

In [49]:
arr1=np.ones (4)
arr2=np.full(4,3)

In [50]:
result= sum(arr1,arr2)
result

array([7., 7., 7., 7.])

In [51]:
result= arr1/arr2

In [52]:
result

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [53]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]

In [54]:
greater_than_2 

array([False, False,  True,  True])

In [55]:
max_value=arr.max()
min_value=arr.min()
summation=arr.sum()
mean_value=arr.mean()
std_deviation=arr.std()

In [56]:
print(mean_value)


2.5


In [57]:
print(std_deviation)

1.118033988749895


# Linear algebra 

- Vector operations
- Multiplication
- Vector-vector multiplication
- Matrix-vector multiplication
- Matrix-matrix multiplication
- Identity matrix
- Inverse

## Vector Operations 

In [58]:
u=np.array([2,3,4,5])
v=np.array([7,8,9,3])

u+ v

array([ 9, 11, 13,  8])

In [59]:
u-v

array([-5, -5, -5,  2])

In [60]:
2*v

array([14, 16, 18,  6])

In [61]:
type(u.shape[0])

int

## Vector Multiplication

In [62]:
def vector_vectpor_multiplication (u,v):
    assert u.shape[0]==v.shape[0], "the dimensions of both vectors must be the same"
    n= u.shape[0]
    container=[]
    for x in range(n):
        dot=u[x]*v[x]
        container.append(dot)
    result_mul= sum(container)
    return result_mul
        

In [63]:
dot_product=vector_vectpor_multiplication(u,v)

In [64]:
dot_product

np.int64(89)

In [65]:
def vector_vector_multiplication1(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [66]:
dot_product=vector_vector_multiplication1(u,v)
dot_product

np.float64(89.0)

## Matrix vector multiplication

In [67]:
def matrix_vector_multiplication(v,u):
    
    assert u.shape[0]==v.shape[1], "number of vector rows(entries) must match matrix column number"
    n=v.shape[0]
    r=v.shape[1]
    container=[]
    for i in range(n):
        s=0
        for q in range(r):
            s=s+v[i,q]*u[q]
        container.append(s)
    return container 
        
            

In [68]:
u=np.array([1,3])
v=np.array([[3,2],[2,1],[2,2]])

In [69]:
matrix_vector_multiplication(v,u)

[np.int64(9), np.int64(5), np.int64(8)]

In [70]:
v

array([[3, 2],
       [2, 1],
       [2, 2]])

In [71]:
v.shape

(3, 2)

In [72]:
v[0,1]

np.int64(2)

In [73]:
u[0]

np.int64(1)

In [74]:
def matrix_matrix_multiplication (U,V):
    assert U.shape[1]==V.shape[0], "The number of columns in 𝐴 must equal the number of rows in 𝐵"
    C= np.zeros([U.shape[0],V.shape[1]])
    n= C.shape[0]
    r=C.shape[1]
    for n in range(n):
        C[n,:]= matrix_vector_multiplication(V,U[n,:])
    return C
        

In [75]:
A=np.array([[7,8],[9,10]])
B=np.array([[1,2],[3,4],[5,6]])

In [76]:
matrix_matrix_multiplication(B,A)

array([[ 23.,  29.],
       [ 53.,  67.],
       [ 83., 105.]])

In [77]:
C= np.zeros([2,3])
C

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
V.shape[1]

2